version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: admin123
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

